## 一、异常的概述

> 在Java语言中，将程序执行中发生的不正常情况称为**异常**。

### 1.异常分类

Java程序在执行过程中所发生的异常时间可分为两类：

* **Error**：Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况（如：StackOverflowError和OOM）。一般不编写针对性的代码。
* **Exception**：其他因程序错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。捕获异常最理想的是在编译期间，但有的错误只有在运行时才会发生，故又分为**编译时异常**和**运行时异常**。

### 2.编译时异常和运行时异常

#### (1)编译时异常

* A: IOCxception
* * a: FileNotFoundException

* B: ClassNotFountException

#### (2)运行时异常

* NullPointerException
 ```java
    // NullPointerException
    	@Test
    	public void test1() {
    		// int[] arr = null;
    		// System.out.println(arr[3]);
    
    		String str = "abc";
    		str = null;
    		System.out.println(str.charAt(0));
    	}
 ```

* ArrayIndexOutOfBoundsException

```java
  // ArrayIndexOutOfBoundsException
  	@Test
  	public void test2() {
  		// int[] arr = new int[10];
  		// System.out.println(arr[10]);
  
  		String str = "abc";
  		System.out.println(str.charAt(3));
  	}
```

* ClassCastException

```java
  // ClassCaseException
  	@Test
  	public void test3() {
  		 Object obj = new Date();
  		 String str = (String)obj;
  	}
```

* NumberFormatException

```java
  // NumberFormatException
  	@Test
  	public void test4() {
  		String str = "123";
  		str = "abc";
  		int num = Integer.parseInt(str);
  	}
```

* InputMismatchException

```java
  	// InputMismatchException
  	@Test
  	public void test5() {
  		Scanner scanner = new Scanner(System.in);
  		int score = scanner.nextInt();
  		System.out.println(score);
  
  		scanner.close();
  	}
```

* ArithmeticException

```java
  	// ArithmeticException
  	@Test
  	public void test6() {
  		int a = 10;
  		int b = 0;
  		System.out.println(a / b);
  	}
```

## 二、异常的处理

> 异常处理：抓抛模型
>
> 过程一：“抛”：程序在正常执行的过程中，一旦出现异常，就会在异常 代码出生成一个对应异常类的对象。并将此对象抛出。一旦抛出对象后，其后的代码不再执行。
>
> 过程二：“抓”：可以理解为异常的处理方式：1.try-catch-finally 2.throws
>
> > Java采用的异常处理机制，是将异常处理的程序代码集中在一起，与正常的程序代码分开，使得程序简洁、优雅，并易于维护。
> >
> > 关于异常对象的产生:① 系统自动生成的异常对象② 手动生成一个异常对象，并抛出(throw)

### 1.异常的处理机制一

#### (1)try-catch-finally

```java
try{
 		//可能出现异常的代码
 }catch(异常类型1 变量名1){
 		//处理异常的方式1
 }catch(异常类型2 变量名2){
 		//处理异常的方式2
 }catch(异常类型3 变量名3){
 		//处理异常的方式3
 }
 ...
 finally{
 		//一定会执行的代码
 }
```

#### (2)try

> 捕获异常的第一步是使用try{...}语句块选定捕获异常的范围，将可能出现异常的代码块放在try语句块中。

#### (3)catch

> 在catch语句块中是对异常对象进行处理的代码块。每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象。 格式：catch(异常类型 形参名)

#### (4)finally

* finally是可选的
* finally中声明的是一定会被执行的代码。即使catch中又出现异常了，try中又有return语句，catch中有return语句等情况。
* 像数据库连接、输入输出流、网络编程Socket等资源，JVM是不能自动的回收的，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在**finally中**。

#### (5)捕获异常信息的相关信息

> 与其他对象一样，可以访问一个异常对象的成员变量或调用它的方法。

* getMessage()：获取异常信息，返回字符串。
* printStackTrace()：获取异常类名和异常信息，以及异常出现在程序中的位置，返回void。

#### (6)说明

* 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配。
 * 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。一旦处理完成，就跳出当前的try-catch结构（在没有写finally的情况）。继续执行其后的代码。
 * catch中的异常类型如果**没有子父类关系**，则谁声明在上，谁声明在下**无所谓**。catch中的异常类型如果**满足子父类关系**，则要求**子类一定声明在父类的上面**。否则，报错
 * 常用的异常对象处理的方式： ① String  getMessage()    ② printStackTrace()
 * 在try结构中声明的变量，再**出了try结构**以后，就**不能再被调用**。
 * try-catch-finally结构可以嵌套  
 * **体会1**：使用try-catch-finally处理编译时异常，是得程序在编译时就不再报错，但是运行时仍可能报错。相当于我们使用try-catch-finally将一个编译时可能出现的异常，延迟到运行时出现。
 * **体会2**：开发中，由于运行时异常比较常见，所以我们通常就不针对运行时异常编写try-catch-finally了。针对于编译时异常，我们说一定要考虑异常的处理。

### 2.异常的处理机制二

> **throws + 异常类型**
>
> * 如果一个方法(中的语句执行时)可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。
>
> - 在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。

 * **"throws + 异常类型"写在方法的声明处**。指明此方法执行时，可能会抛出的异常类型。一旦当方法体执行时，出现异常，仍会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出。异常代码后续的代码，就不再执行！
 * try-catch-finally:真正的将异常给处理掉了。throws的方式只是将异常**抛给**了方法的**调用者**。  并没有真正将异常处理掉。

```java
public class ExceptionTest2 {
	
	public static void main(String[] args){
		try {
			method2();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		method3();
	}
	
	public static void method3(){
		try {
			method2();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public static void method2() throws IOException{
		method1();
	}

	
	public static void method1() throws FileNotFoundException,IOException{
		File file = new File("hello1.txt");
		FileInputStream fis = new FileInputStream(file);
		
		int data = fis.read();
		while(data != -1){
			System.out.print((char)data);
			data = fis.read();
		}
		
		fis.close();
		
		System.out.println("hahaha!");
	}
}
```

**重写方法抛出异常的原则**：子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型

```java
public class OverrideTest {
	
	public static void main(String[] args) {
		OverrideTest test = new OverrideTest();
		test.display(new SubClass());
	}
	
	public void display(SuperClass s){
		try {
			s.method();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
}
class SuperClass{
	
	public void method() throws IOException{
		
	}
}
class SubClass extends SuperClass{
	public void method()throws FileNotFoundException{
		
	}
}
```

**开发中如何选择使用try-catch-finally 还是使用throws?**

 *   如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally方式处理。
 *   执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑使用try-catch-finally方式进行处理。





## 三、手动抛出异常

> Java异常类对象除在程序执行过程中出现异常时由系统自动生成并抛出，也可根据需要使用人工创建并抛出。

- 首先要生成异常类对象，然后通过throw语句实现抛出操作(提交给Java运行环境)
- 可以抛出的异常必须是Throwable或其子类的实例。

```java
public class StudentTest {
	public static void main(String[] args) {
		try {
			Student s = new Student();
//		s.regist(1001);
			s.regist(-1001);
			System.out.println(s);
		} catch (Exception e) {
//			e.printStackTrace();
			System.out.println(e.getMessage());
		}
	}
}
class Student{
	private int id;
	
	public void regist(int id) throws Exception{
		if(id > 0){
			this.id = id;
		}else{
//			System.out.println("您输入的数据非法！");
			//手动抛出异常
//			throw new RuntimeException("您输入的数据非法！");
			throw new Exception("您输入的数据非法！");
			
		}
	}

	@Override
	public String toString() {
		return "Student [id=" + id + "]";
	}
	
}
```

## 四、自定义异常类

> - 一般地，用户自定义异常类都是RuntimeException的子类。
> - 自定义异常类通常需要编写几个重载的构造器。
> - 自定义异常需要提供serialVersionUID
> - 自定义的异常通过throw抛出。
> - 自定义异常最重要的是异常类的名字，当异常出现时，可以根据名字判断异常类型。

```java
/*
 * 如何自定义异常类？
 * 1.继承于现有的异常结构：RuntimeException 、Exception
 * 2.提供全局常量：serialVersionUID
 * 3.提供重载的构造器
 * 
 */
public class MyException extends RuntimeException{
	static final long serialVersionUID = -7034897193246939L;
	
	public MyException(){
		
	}
	
	public MyException(String msg){
		super(msg);
	}
}
```



